/**
 * Airport code to city name mapping
 * Maps IATA airport codes to their corresponding city and country
 */

export const getLocationFromAirportCode = (airportCode: string): string => {
  const airportToCity: Record<string, string> = {
    // Major international airports
    'JFK': 'New York, USA',
    'LGA': 'New York, USA', 
    'EWR': 'New York, USA',
    'LHR': 'London, UK',
    'LGW': 'London, UK',
    'STN': 'London, UK',
    'LTN': 'London, UK',
    'CDG': 'Paris, France',
    'ORY': 'Paris, France',
    'DXB': 'Dubai, UAE',
    'AUH': 'Abu Dhabi, UAE',
    'DOH': 'Doha, Qatar',
    'SIN': 'Singapore',
    'HKG': 'Hong Kong',
    'NRT': 'Tokyo, Japan',
    'HND': 'Tokyo, Japan',
    'ICN': 'Seoul, South Korea',
    'PVG': 'Shanghai, China',
    'PEK': 'Beijing, China',
    'SYD': 'Sydney, Australia',
    'MEL': 'Melbourne, Australia',
    'YYZ': 'Toronto, Canada',
    'YVR': 'Vancouver, Canada',
    'LAX': 'Los Angeles, USA',
    'SFO': 'San Francisco, USA',
    'ORD': 'Chicago, USA',
    'MIA': 'Miami, USA',
    'ATL': 'Atlanta, USA',
    'DEN': 'Denver, USA',
    'SEA': 'Seattle, USA',
    'BOS': 'Boston, USA',
    'IAD': 'Washington DC, USA',
    'DCA': 'Washington DC, USA',
    'BWI': 'Baltimore, USA',
    'PHL': 'Philadelphia, USA',
    'DTW': 'Detroit, USA',
    'MSP': 'Minneapolis, USA',
    'PHX': 'Phoenix, USA',
    'LAS': 'Las Vegas, USA',
    'MCO': 'Orlando, USA',
    'FLL': 'Fort Lauderdale, USA',
    'TPA': 'Tampa, USA',
    'CLT': 'Charlotte, USA',
    'DFW': 'Dallas, USA',
    'IAH': 'Houston, USA',
    'SLC': 'Salt Lake City, USA',
    'PDX': 'Portland, USA',
    'SAN': 'San Diego, USA',
    
    // Nigerian airports
    'LOS': 'Lagos, Nigeria',
    'ABV': 'Abuja, Nigeria',
    'PHC': 'Port Harcourt, Nigeria',
    'KAN': 'Kano, Nigeria',
    'IBD': 'Ibadan, Nigeria',
    'ENU': 'Enugu, Nigeria',
    'CBQ': 'Calabar, Nigeria',
    'ILR': 'Ilorin, Nigeria',
    'AKR': 'Akure, Nigeria',
    'BNI': 'Benin City, Nigeria',
    'MDI': 'Makurdi, Nigeria',
    'JOS': 'Jos, Nigeria',
    'MIU': 'Maiduguri, Nigeria',
    'YOL': 'Yola, Nigeria',
    'GMO': 'Gombe, Nigeria',
    'KAD': 'Kaduna, Nigeria',
    'ZAR': 'Zaria, Nigeria',
    'SKO': 'Sokoto, Nigeria',
    'KTG': 'Katsina, Nigeria',
    'DUT': 'Dutse, Nigeria',
    'GUS': 'Gusau, Nigeria',
    'BKC': 'Bauchi, Nigeria',
    'UYO': 'Uyo, Nigeria',
    'OWE': 'Owerri, Nigeria',
    'ASO': 'Asaba, Nigeria',
    'WRR': 'Warri, Nigeria',
    
    // African airports
    'CAI': 'Cairo, Egypt',
    'ALG': 'Algiers, Algeria',
    'CAS': 'Casablanca, Morocco',
    'RAK': 'Marrakech, Morocco',
    'TUN': 'Tunis, Tunisia',
    'ACC': 'Accra, Ghana',
    'ABJ': 'Abidjan, Ivory Coast',
    'DKR': 'Dakar, Senegal',
    'COO': 'Cotonou, Benin',
    'LFW': 'Lome, Togo',
    'ADD': 'Addis Ababa, Ethiopia',
    'NBO': 'Nairobi, Kenya',
    'EBB': 'Entebbe, Uganda',
    'KGL': 'Kigali, Rwanda',
    'DAR': 'Dar es Salaam, Tanzania',
    'JNB': 'Johannesburg, South Africa',
    'CPT': 'Cape Town, South Africa',
    'DUR': 'Durban, South Africa',
    'WDH': 'Windhoek, Namibia',
    'LAD': 'Luanda, Angola',
    'MPM': 'Maputo, Mozambique',
    'BEW': 'Beira, Mozambique',
    'LUN': 'Lusaka, Zambia',
    'HAR': 'Harare, Zimbabwe',
    'GBE': 'Gaborone, Botswana',
    'MSU': 'Maseru, Lesotho',
    
    // European airports
    'FCO': 'Rome, Italy',
    'MXP': 'Milan, Italy',
    'VCE': 'Venice, Italy',
    'NAP': 'Naples, Italy',
    'MAD': 'Madrid, Spain',
    'BCN': 'Barcelona, Spain',
    'PMI': 'Palma, Spain',
    'AGP': 'Malaga, Spain',
    'LIS': 'Lisbon, Portugal',
    'OPO': 'Porto, Portugal',
    'FRA': 'Frankfurt, Germany',
    'MUC': 'Munich, Germany',
    'DUS': 'Dusseldorf, Germany',
    'BER': 'Berlin, Germany',
    'HAM': 'Hamburg, Germany',
    'AMS': 'Amsterdam, Netherlands',
    'BRU': 'Brussels, Belgium',
    'ZUR': 'Zurich, Switzerland',
    'GVA': 'Geneva, Switzerland',
    'VIE': 'Vienna, Austria',
    'CPH': 'Copenhagen, Denmark',
    'ARN': 'Stockholm, Sweden',
    'GOT': 'Gothenburg, Sweden',
    'OSL': 'Oslo, Norway',
    'BGO': 'Bergen, Norway',
    'HEL': 'Helsinki, Finland',
    'KEF': 'Reykjavik, Iceland',
    
    // Middle Eastern airports
    'RUH': 'Riyadh, Saudi Arabia',
    'JED': 'Jeddah, Saudi Arabia',
    'DMM': 'Dammam, Saudi Arabia',
    'KWI': 'Kuwait City, Kuwait',
    'BAH': 'Manama, Bahrain',
    'MCT': 'Muscat, Oman',
    'SHJ': 'Sharjah, UAE',
    'IKA': 'Tehran, Iran',
    'DAM': 'Damascus, Syria',
    'BGW': 'Baghdad, Iraq',
    'AMM': 'Amman, Jordan',
    'BEY': 'Beirut, Lebanon',
    'TLV': 'Tel Aviv, Israel',
    'IST': 'Istanbul, Turkey',
    'SAW': 'Istanbul, Turkey',
    'ADB': 'Izmir, Turkey',
    'AYT': 'Antalya, Turkey',
    'ANK': 'Ankara, Turkey',
    
    // Asian airports
    'BOM': 'Mumbai, India',
    'DEL': 'Delhi, India',
    'BLR': 'Bangalore, India',
    'MAA': 'Chennai, India',
    'CCU': 'Kolkata, India',
    'HYD': 'Hyderabad, India',
    'AMD': 'Ahmedabad, India',
    'COK': 'Kochi, India',
    'GOI': 'Goa, India',
    'PER': 'Perth, Australia',
    'ADL': 'Adelaide, Australia',
    'BNE': 'Brisbane, Australia',
    'CNS': 'Cairns, Australia',
    'DRW': 'Darwin, Australia',
    'AKL': 'Auckland, New Zealand',
    'CHC': 'Christchurch, New Zealand',
    'WLG': 'Wellington, New Zealand',
    'ZQN': 'Queenstown, New Zealand',
    'PPT': 'Papeete, French Polynesia',
    'NOU': 'Noumea, New Caledonia',
    'POM': 'Port Moresby, Papua New Guinea',
    
    // Additional airports
    'ATH': 'Athens, Greece',
    'SKG': 'Thessaloniki, Greece',
    'RHO': 'Rhodes, Greece',
    'HER': 'Heraklion, Greece',
    'CFU': 'Corfu, Greece',
    'JMK': 'Mykonos, Greece',
    'JTR': 'Santorini, Greece',
    'KGS': 'Kos, Greece',
    'EDI': 'Edinburgh, Scotland',
    'GLA': 'Glasgow, Scotland',
    'ABZ': 'Aberdeen, Scotland',
    'INV': 'Inverness, Scotland',
    'CWL': 'Cardiff, Wales',
    'SWS': 'Swansea, Wales',
    'BHD': 'Belfast, Northern Ireland',
    'BFS': 'Belfast, Northern Ireland',
    'BHX': 'Birmingham, England',
    'MAN': 'Manchester, England',
    'LPL': 'Liverpool, England',
    'NCL': 'Newcastle, England',
    'LEE': 'Leeds, England',
    'SOU': 'Southampton, England',
    'BOH': 'Bournemouth, England',
    'EXT': 'Exeter, England',
    'PLH': 'Plymouth, England',
    'NQY': 'Newquay, England',
    'BRS': 'Bristol, England',
    'IOM': 'Isle of Man',
    'JER': 'Jersey, Channel Islands',
    'GCI': 'Guernsey, Channel Islands'
  };

  return airportToCity[airportCode] || airportCode;
};